language: node_js
node_js:
- 4.3.1
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: 9a0524d06a72b026a3d9b1ad9c889d3e11a69311be659448086a0327651439f2
deploy:
  provider: npm
  email: technique@yocto.re
  api_key:
    secure: ZTAkcZNFcfqkNQ/FXBXKUx9A2FaQbKz+ii/kg2EFQrZc7xb6YSvK2Qkxeg6N83BGUJE8yyvv9F8XPC38aqnyLpwiHEKKMHf9UkgxjZzPpXUACeCVNEWCgQI1IGrOl7qRLI1mTB6GDSie5nh2LQoTf1lQZm+bX0603Dkrvg4agPVm6sTRlqPLET6l6myimH3XLyyEz5BUc6KftuZ7IJewww+o0LQqsqkcc1LEtxzPM1aoCkZnMzuXItcU3kOk5UYH22aLm/t9tsxyQ69vqYcBjaCbgViO1k1pzIoKN07iEMOXNJDJYIHwRStvqjEIp6NhBFhsb6f1eC5yiquZYT/EBogFPsC+Q2qsPKs3pl+ayEoEjr1v0WIgfbPmtR/4fsfgCtkVBXfw8wt78zWP7lXoaut6U/SojhT9NogakGirMM/pedv0jowQXq1sUF76w0QY/4FrlqNZKOrK5aeDjZd++u5zGlR2ta5zNbOlYNzKNfo3Y8s5Zj1/A2ev3aNcvUCpcNakURXy/Agi1Ms0DsdiiLhMNEjwFUL8uZibxxVJzH+eG7280hYziVjkgkmgq4uIUR1JAkUSNWJYJ2pYr53nkZrTC59E+cBrSYDdAqHwq39XD6eru1KmvVCs0mamRJa+5ZcSJYWqzwJuHhcfklYUxJC4AD0G3PbB724WXsMMJSI=
  on:
    tags: true
    repo: yoctore/yoctopus-generator
before_install: npm install -g grunt-cli
install: npm install
